image: python:3.10-alpine

variables:
  https_proxy: http://proxy.charite.de:8080
  http_proxy: http://proxy.charite.de:8080

pylint:
  stage: test
  script:
    - pip install -U flake8
    - python -m flake8

package:
  stage: deploy
  only:
  - tags
  script:
  - pip install build twine
  - python -m build
  - twine check dist/*
  - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
